export const ICS = [
  { id: 1, icName: 'Star Health Insurance',  code: 'SHI', contactPerson: 'Ravi Sharma',   contactEmail: 'ravi.sharma@starhealth.in',        email: 'api@starhealth.in',        phone: '+91 98765 43210', apiBaseUrl: 'https://api.starhealth.in/v1',        apiKey: 'sk_live_shi_abc123', apiSecret: 'secret_shi_xyz789', status: 'Active'   },
  { id: 2, icName: 'HDFC ERGO',              code: 'HER', contactPerson: 'Neha Joshi',    contactEmail: 'neha.joshi@hdfcergo.com',           email: 'api@hdfcergo.com',         phone: '+91 99887 65432', apiBaseUrl: 'https://api.hdfcergo.com/v2',         apiKey: 'sk_live_her_def456', apiSecret: 'secret_her_uvw321', status: 'Active'   },
  { id: 3, icName: 'ICICI Lombard',          code: 'ICL', contactPerson: 'Amit Patel',    contactEmail: 'amit.patel@icicilombard.com',       email: 'api@icicilombard.com',     phone: '+91 98011 22334', apiBaseUrl: 'https://api.icicilombard.com/v1',     apiKey: 'sk_live_icl_ghi789', apiSecret: 'secret_icl_rst654', status: 'Active'   },
  { id: 4, icName: 'Bajaj Allianz',          code: 'BAJ', contactPerson: 'Sunita Rao',    contactEmail: 'sunita.rao@bajajallianz.com',       email: 'api@bajajallianz.com',     phone: '+91 98989 89898', apiBaseUrl: 'https://api.bajajallianz.com/v1',    apiKey: 'sk_live_baj_jkl012', apiSecret: 'secret_baj_opq987', status: 'Inactive' },
  { id: 5, icName: 'New India Assurance',    code: 'NIA', contactPerson: 'Prakash Mehta', contactEmail: 'prakash.mehta@newindia.co.in',      email: 'api@newindia.co.in',       phone: '+91 99112 23344', apiBaseUrl: 'https://api.newindia.co.in/v2',      apiKey: 'sk_live_nia_mno345', apiSecret: 'secret_nia_lmn320', status: 'Active'   },
  { id: 6, icName: 'United India Insurance', code: 'UII', contactPerson: 'Rekha Nair',    contactEmail: 'rekha.nair@uiic.co.in',             email: 'api@uiic.co.in',           phone: '+91 99223 34455', apiBaseUrl: 'https://api.uiic.co.in/v1',          apiKey: 'sk_live_uii_pqr678', apiSecret: 'secret_uii_ijk653', status: 'Active'   },
  { id: 7, icName: 'Reliance General',       code: 'RGI', contactPerson: 'Suresh Kumar',  contactEmail: 'suresh.kumar@reliancegeneral.in',   email: 'api@reliancegeneral.in',   phone: '+91 99334 45566', apiBaseUrl: 'https://api.reliancegeneral.in/v1',  apiKey: 'sk_live_rgi_stu901', apiSecret: 'secret_rgi_fgh986', status: 'Active'   },
  { id: 8, icName: 'Tata AIG',               code: 'TAI', contactPerson: 'Aarti Singh',   contactEmail: 'aarti.singh@tataaig.com',           email: 'api@tataaig.com',          phone: '+91 99445 56677', apiBaseUrl: 'https://api.tataaig.com/v2',          apiKey: 'sk_live_tai_vwx234', apiSecret: 'secret_tai_cde319', status: 'Inactive' },
  { id: 9, icName: 'Oriental Insurance',     code: 'OIC', contactPerson: 'Vijay Sharma',  contactEmail: 'vijay.sharma@orientalinsurance.in', email: 'api@orientalinsurance.in', phone: '+91 99556 67788', apiBaseUrl: 'https://api.orientalinsurance.in/v1', apiKey: 'sk_live_oic_yza567', apiSecret: 'secret_oic_zab652', status: 'Active'   },
]

export const IC_MAP = Object.fromEntries(ICS.map(ic => [ic.id, ic]))
