export const POLICY_TYPES = {
  1: 'Base Policy',
  2: 'Top Up Policy',
  3: 'OPD',
  4: 'Payment Protection',
  5: 'Age Band Premium',
  6: 'Super Top Up',
  999: 'Other',
}

export const POLICY_TYPE_COLOR = {
  'Base Policy':        'blue',
  'OPD':                'green',
  'Payment Protection': 'amber',
  'Age Band Premium':   'purple',
  'Super Top Up':       'red',
  'Top Up Policy':      'blue',
  'Other':              'gray',
}

export const POLICY_TYPE_ICON = {
  'Base Policy':        '🏥',
  'OPD':                '💊',
  'Payment Protection': '🛡️',
  'Age Band Premium':   '👨‍👩‍👧',
  'Super Top Up':       '⬆️',
  'Top Up Policy':      '📈',
  'Other':              '📋',
}

// All products — IsActive=0 records (37, 41) are excluded
const ALL_PRODUCTS = [
  {
    id: 3,
    name: 'Super Top Up Policy',
    provider: 'Go Digit',
    policyTypeId: 1,
    disclaimer: null,
  },
  {
    id: 6,
    name: 'Test Base Product',
    provider: 'LIC',
    policyTypeId: 1,
    disclaimer: null,
  },
  {
    id: 7,
    name: 'OUT-PATIENT CARE INSURANCE POLICY',
    provider: 'Go Digit General Insurance Limited',
    policyTypeId: 3,
    disclaimer: null,
  },
  {
    id: 8,
    name: 'DIGIT PAYMENT PROTECTION POLICY',
    provider: 'Go Digit General Insurance Limited',
    policyTypeId: 4,
    disclaimer: null,
  },
  {
    id: 9,
    name: 'Group Health Insurance Policy for BPP',
    provider: 'MAGMA GENERAL INSURANCE LIMITED',
    policyTypeId: 5,
    disclaimer: 'I hereby declare, on my behalf and on behalf of my Family, that the above particulars given by me are true and complete in all respects to the best of my knowledge and that I am authorized to propose on behalf of my Family. I understand that the information provided by me will form the basis of the insurance policy, and that the policy will come into force only after full receipt of the premium chargeable and the application is in order. I agree to the terms and conditions of the Policy and have understood the same.',
  },
  {
    id: 10,
    name: 'Standalone Super Top Up Policy (BPP)',
    provider: 'MAGMA GENERAL INSURANCE LIMITED',
    policyTypeId: 5,
    disclaimer: 'I hereby declare, on my behalf and on behalf of my spouse, that the above particulars given by me are true and complete in all respects to the best of my knowledge and that I am authorized to propose on behalf of my spouse. I understand that the information provided by me will form the basis of the insurance policy, and that the policy will come into force only after full receipt of the premium chargeable and the application is in order. I agree to the terms and conditions of the Policy and have understood the same.',
  },
  {
    id: 11,
    name: 'Group Health Insurance Policy for BPP_New',
    provider: 'Oriental Insurance Co. Ltd.',
    policyTypeId: 5,
    disclaimer: 'I hereby declare, on my behalf and on behalf of my Family, that the above particulars given by me are true and complete in all respects to the best of my knowledge and that I am authorized to propose on behalf of my Family. I understand that the information provided by me will form the basis of the insurance policy, and that the policy will come into force only after full receipt of the premium chargeable and the application is in order. I agree to the terms and conditions of the Policy and have understood the same.',
  },
  {
    id: 12,
    name: 'Standalone Super Top Up Policy_BPP_New',
    provider: 'Oriental Insurance Co. Ltd.',
    policyTypeId: 5,
    disclaimer: 'I hereby declare, on my behalf and on behalf of my Family, that the above particulars given by me are true and complete in all respects to the best of my knowledge and that I am authorized to propose on behalf of my Family. I understand that the information provided by me will form the basis of the insurance policy, and that the policy will come into force only after full receipt of the premium chargeable and the application is in order. I agree to the terms and conditions of the Policy and have understood the same.',
  },
  {
    id: 38,
    name: 'For Threshold of 3 Lakhs — Super Top Up Policy',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 6,
    disclaimer: null,
    linkedBaseId: 42,
    bundleDiscount: { type: 'Percent', value: 10 },
  },
  {
    id: 39,
    name: 'For Threshold of 4 Lakhs — Super Top Up Policy',
    provider: 'SBI General Insurance Co. Ltd.',
    policyTypeId: 6,
    disclaimer: null,
    linkedBaseId: 42,
    bundleDiscount: { type: 'Percent', value: 8 },
  },
  {
    id: 40,
    name: 'For Threshold of 5 Lakhs — Super Top Up Policy',
    provider: 'SBI General Insurance Co. Ltd.',
    policyTypeId: 6,
    disclaimer: null,
    linkedBaseId: 42,
    bundleDiscount: { type: 'Percent', value: 5 },
  },
  {
    id: 42,
    name: 'SBI Base Policy',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 1,
    disclaimer: null,
  },
  {
    id: 43,
    name: 'OPD Policy-2025-26',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 3,
    disclaimer: null,
  },
  {
    id: 44,
    name: 'Group Health Insurance Policy for BPP_2026-2027',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 5,
    disclaimer: 'I hereby declare, on my behalf and on behalf of my Family, that the above particulars given by me are true and complete in all respects to the best of my knowledge and that I am authorized to propose on behalf of my Family. I understand that the information provided by me will form the basis of the insurance policy, and that the policy will come into force only after full receipt of the premium chargeable and the application is in order. I agree to the terms and conditions of the Policy and have understood the same.',
  },
  {
    id: 45,
    name: 'Standalone Super Top Up Policy_BPP_2026-2027',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 5,
    disclaimer: 'I hereby declare, on my behalf and on behalf of my Family, that the above particulars given by me are true and complete in all respects to the best of my knowledge and that I am authorized to propose on behalf of my Family. I understand that the information provided by me will form the basis of the insurance policy, and that the policy will come into force only after full receipt of the premium chargeable and the application is in order. I agree to the terms and conditions of the Policy and have understood the same.',
  },
  {
    id: 46,
    name: 'Standalone',
    provider: 'Sainath',
    policyTypeId: 1,
    disclaimer: 'hhz',
  },
  {
    id: 47,
    name: 'testP',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 1,
    disclaimer: 'test',
  },
  {
    id: 48,
    name: 'SBI Arogya Plus — Top Up Health Plan',
    provider: 'SBI General Insurance Company Limited',
    policyTypeId: 2,
    disclaimer: null,
    linkedBaseId: 42,
    bundleDiscount: { type: 'Percent', value: 15 },
  },
]

// Enrich each product with derived display fields
export const PRODUCTS = ALL_PRODUCTS.map(p => ({
  ...p,
  code: `KMD-${String(p.id).padStart(3, '0')}`,
  policyType: POLICY_TYPES[p.policyTypeId] ?? 'Other',
  status: 'Active',
}))

// Grouped by policyType name — used in BuyPolicy wizard
export const PRODUCTS_BY_TYPE = PRODUCTS.reduce((acc, p) => {
  const type = p.policyType
  if (!acc[type]) acc[type] = []
  acc[type].push(p)
  return acc
}, {})

// Premium chart keyed by productId.
// Fields: sumInsured, selfOnly, selfSpouse, selfSpouse2Children (omitted when 0), ageBandId (omitted when 0).
export const PREMIUM_CHART = {
  3: [
    { sumInsured: 100000,  selfOnly: 2430,   selfSpouse: 4130 },
    { sumInsured: 200000,  selfOnly: 3887,   selfSpouse: 6610 },
    { sumInsured: 300000,  selfOnly: 5509,   selfSpouse: 9366 },
    { sumInsured: 400000,  selfOnly: 8097,   selfSpouse: 13765 },
    { sumInsured: 500000,  selfOnly: 10306,  selfSpouse: 17156 },
    { sumInsured: 600000,  selfOnly: 16052,  selfSpouse: 26301 },
    { sumInsured: 700000,  selfOnly: 22514,  selfSpouse: 37892 },
    { sumInsured: 800000,  selfOnly: 37312,  selfSpouse: 62505 },
    { sumInsured: 900000,  selfOnly: 53078,  selfSpouse: 91470 },
    { sumInsured: 1000000, selfOnly: 64092,  selfSpouse: 107569 },
  ],
  6: [
    { sumInsured: 10, selfOnly: 1, selfSpouse: 2 },
  ],
  7: [
    { sumInsured: 15000, selfOnly: 10385, selfSpouse: 10385 },
    { sumInsured: 20000, selfOnly: 11727, selfSpouse: 11727 },
  ],
  8: [
    { sumInsured: 50000,  selfOnly: 998 },
    { sumInsured: 100000, selfOnly: 1997 },
  ],
  9: [
    { sumInsured: 300000,  ageBandId: 1,  selfOnly: 8459,   selfSpouse: 13178,  selfSpouse2Children: 19194 },
    { sumInsured: 300000,  ageBandId: 2,  selfOnly: 9185,   selfSpouse: 14330,  selfSpouse2Children: 21076 },
    { sumInsured: 300000,  ageBandId: 3,  selfOnly: 11309,  selfSpouse: 17697,  selfSpouse2Children: 24833 },
    { sumInsured: 300000,  ageBandId: 4,  selfOnly: 16496,  selfSpouse: 27214,  selfSpouse2Children: 32437 },
    { sumInsured: 300000,  ageBandId: 5,  selfOnly: 20560,  selfSpouse: 33919,  selfSpouse2Children: 40428 },
    { sumInsured: 300000,  ageBandId: 6,  selfOnly: 23914,  selfSpouse: 37248,  selfSpouse2Children: 41409 },
    { sumInsured: 300000,  ageBandId: 7,  selfOnly: 26369,  selfSpouse: 43415,  selfSpouse2Children: 58009 },
    { sumInsured: 300000,  ageBandId: 8,  selfOnly: 36165,  selfSpouse: 64603,  selfSpouse2Children: 77137 },
    { sumInsured: 300000,  ageBandId: 9,  selfOnly: 47057,  selfSpouse: 86290,  selfSpouse2Children: 101437 },
    { sumInsured: 300000,  ageBandId: 10, selfOnly: 55959,  selfSpouse: 102615, selfSpouse2Children: 120625 },
    { sumInsured: 300000,  ageBandId: 11, selfOnly: 64691,  selfSpouse: 118626, selfSpouse2Children: 139448 },
    { sumInsured: 500000,  ageBandId: 1,  selfOnly: 9462,   selfSpouse: 14750,  selfSpouse2Children: 21401 },
    { sumInsured: 500000,  ageBandId: 2,  selfOnly: 10309,  selfSpouse: 16082,  selfSpouse2Children: 23593 },
    { sumInsured: 500000,  ageBandId: 3,  selfOnly: 12799,  selfSpouse: 20029,  selfSpouse2Children: 28022 },
    { sumInsured: 500000,  ageBandId: 4,  selfOnly: 18687,  selfSpouse: 30830,  selfSpouse2Children: 36617 },
    { sumInsured: 500000,  ageBandId: 5,  selfOnly: 23545,  selfSpouse: 38843,  selfSpouse2Children: 46134 },
    { sumInsured: 500000,  ageBandId: 6,  selfOnly: 27528,  selfSpouse: 42874,  selfSpouse2Children: 47488 },
    { sumInsured: 500000,  ageBandId: 7,  selfOnly: 31177,  selfSpouse: 51338,  selfSpouse2Children: 68396 },
    { sumInsured: 500000,  ageBandId: 8,  selfOnly: 42725,  selfSpouse: 76338,  selfSpouse2Children: 90863 },
    { sumInsured: 500000,  ageBandId: 9,  selfOnly: 54991,  selfSpouse: 100863, selfSpouse2Children: 118166 },
    { sumInsured: 500000,  ageBandId: 10, selfOnly: 64458,  selfSpouse: 118227, selfSpouse2Children: 138510 },
    { sumInsured: 500000,  ageBandId: 11, selfOnly: 74555,  selfSpouse: 136749, selfSpouse2Children: 160209 },
    { sumInsured: 750000,  ageBandId: 1,  selfOnly: 11051,  selfSpouse: 17216,  selfSpouse2Children: 24936 },
    { sumInsured: 750000,  ageBandId: 2,  selfOnly: 12045,  selfSpouse: 18778,  selfSpouse2Children: 27500 },
    { sumInsured: 750000,  ageBandId: 3,  selfOnly: 15016,  selfSpouse: 23485,  selfSpouse2Children: 32798 },
    { sumInsured: 750000,  ageBandId: 4,  selfOnly: 21921,  selfSpouse: 36146,  selfSpouse2Children: 42856 },
    { sumInsured: 750000,  ageBandId: 5,  selfOnly: 27883,  selfSpouse: 45974,  selfSpouse2Children: 54507 },
    { sumInsured: 750000,  ageBandId: 6,  selfOnly: 32779,  selfSpouse: 51025,  selfSpouse2Children: 56416 },
    { sumInsured: 750000,  ageBandId: 7,  selfOnly: 38185,  selfSpouse: 62843,  selfSpouse2Children: 83574 },
    { sumInsured: 750000,  ageBandId: 8,  selfOnly: 52243,  selfSpouse: 93294,  selfSpouse2Children: 110848 },
    { sumInsured: 750000,  ageBandId: 9,  selfOnly: 66553,  selfSpouse: 122002, selfSpouse2Children: 142679 },
    { sumInsured: 750000,  ageBandId: 10, selfOnly: 76753,  selfSpouse: 140702, selfSpouse2Children: 164548 },
    { sumInsured: 750000,  ageBandId: 11, selfOnly: 88778,  selfSpouse: 162745, selfSpouse2Children: 190326 },
    { sumInsured: 1000000, ageBandId: 1,  selfOnly: 11726,  selfSpouse: 18252,  selfSpouse2Children: 26414 },
    { sumInsured: 1000000, ageBandId: 2,  selfOnly: 12784,  selfSpouse: 19913,  selfSpouse2Children: 29139 },
    { sumInsured: 1000000, ageBandId: 3,  selfOnly: 15979,  selfSpouse: 24972,  selfSpouse2Children: 34845 },
    { sumInsured: 1000000, ageBandId: 4,  selfOnly: 23329,  selfSpouse: 38434,  selfSpouse2Children: 45530 },
    { sumInsured: 1000000, ageBandId: 5,  selfOnly: 29841,  selfSpouse: 49159,  selfSpouse2Children: 58236 },
    { sumInsured: 1000000, ageBandId: 6,  selfOnly: 35192,  selfSpouse: 54736,  selfSpouse2Children: 60469 },
    { sumInsured: 1000000, ageBandId: 7,  selfOnly: 41648,  selfSpouse: 68485,  selfSpouse2Children: 91003 },
    { sumInsured: 1000000, ageBandId: 8,  selfOnly: 56932,  selfSpouse: 101580, selfSpouse2Children: 120595 },
    { sumInsured: 1000000, ageBandId: 9,  selfOnly: 72114,  selfSpouse: 132084, selfSpouse2Children: 154342 },
    { sumInsured: 1000000, ageBandId: 10, selfOnly: 82405,  selfSpouse: 150934, selfSpouse2Children: 176369 },
    { sumInsured: 1000000, ageBandId: 11, selfOnly: 95314,  selfSpouse: 174579, selfSpouse2Children: 204001 },
  ],
  10: [
    { sumInsured: 300000,  ageBandId: 1,  selfOnly: 2538,   selfSpouse: 3953,   selfSpouse2Children: 5758 },
    { sumInsured: 300000,  ageBandId: 2,  selfOnly: 2755,   selfSpouse: 4299,   selfSpouse2Children: 6323 },
    { sumInsured: 300000,  ageBandId: 3,  selfOnly: 3393,   selfSpouse: 5309,   selfSpouse2Children: 7450 },
    { sumInsured: 300000,  ageBandId: 4,  selfOnly: 4949,   selfSpouse: 8164,   selfSpouse2Children: 9731 },
    { sumInsured: 300000,  ageBandId: 5,  selfOnly: 6168,   selfSpouse: 10176,  selfSpouse2Children: 12128 },
    { sumInsured: 300000,  ageBandId: 6,  selfOnly: 7174,   selfSpouse: 11174,  selfSpouse2Children: 12423 },
    { sumInsured: 300000,  ageBandId: 7,  selfOnly: 7911,   selfSpouse: 13024,  selfSpouse2Children: 17403 },
    { sumInsured: 300000,  ageBandId: 8,  selfOnly: 10850,  selfSpouse: 19381,  selfSpouse2Children: 23141 },
    { sumInsured: 300000,  ageBandId: 9,  selfOnly: 14117,  selfSpouse: 25887,  selfSpouse2Children: 30431 },
    { sumInsured: 300000,  ageBandId: 10, selfOnly: 16788,  selfSpouse: 30784,  selfSpouse2Children: 36188 },
    { sumInsured: 300000,  ageBandId: 11, selfOnly: 19407,  selfSpouse: 35588,  selfSpouse2Children: 41834 },
    { sumInsured: 500000,  ageBandId: 1,  selfOnly: 2649,   selfSpouse: 4130,   selfSpouse2Children: 5992 },
    { sumInsured: 500000,  ageBandId: 2,  selfOnly: 2886,   selfSpouse: 4503,   selfSpouse2Children: 6606 },
    { sumInsured: 500000,  ageBandId: 3,  selfOnly: 3584,   selfSpouse: 5608,   selfSpouse2Children: 7846 },
    { sumInsured: 500000,  ageBandId: 4,  selfOnly: 5232,   selfSpouse: 8633,   selfSpouse2Children: 10253 },
    { sumInsured: 500000,  ageBandId: 5,  selfOnly: 6593,   selfSpouse: 10876,  selfSpouse2Children: 12917 },
    { sumInsured: 500000,  ageBandId: 6,  selfOnly: 7708,   selfSpouse: 12005,  selfSpouse2Children: 13297 },
    { sumInsured: 500000,  ageBandId: 7,  selfOnly: 8730,   selfSpouse: 14375,  selfSpouse2Children: 19151 },
    { sumInsured: 500000,  ageBandId: 8,  selfOnly: 11963,  selfSpouse: 21375,  selfSpouse2Children: 25442 },
    { sumInsured: 500000,  ageBandId: 9,  selfOnly: 15397,  selfSpouse: 28242,  selfSpouse2Children: 33087 },
    { sumInsured: 500000,  ageBandId: 10, selfOnly: 18048,  selfSpouse: 33104,  selfSpouse2Children: 38783 },
    { sumInsured: 500000,  ageBandId: 11, selfOnly: 20875,  selfSpouse: 38290,  selfSpouse2Children: 44858 },
    { sumInsured: 750000,  ageBandId: 1,  selfOnly: 3094,   selfSpouse: 4821,   selfSpouse2Children: 6982 },
    { sumInsured: 750000,  ageBandId: 2,  selfOnly: 3373,   selfSpouse: 5258,   selfSpouse2Children: 7700 },
    { sumInsured: 750000,  ageBandId: 3,  selfOnly: 4204,   selfSpouse: 6576,   selfSpouse2Children: 9183 },
    { sumInsured: 750000,  ageBandId: 4,  selfOnly: 6138,   selfSpouse: 10121,  selfSpouse2Children: 12000 },
    { sumInsured: 750000,  ageBandId: 5,  selfOnly: 7807,   selfSpouse: 12873,  selfSpouse2Children: 15262 },
    { sumInsured: 750000,  ageBandId: 6,  selfOnly: 9178,   selfSpouse: 14287,  selfSpouse2Children: 15796 },
    { sumInsured: 750000,  ageBandId: 7,  selfOnly: 10692,  selfSpouse: 17596,  selfSpouse2Children: 23401 },
    { sumInsured: 750000,  ageBandId: 8,  selfOnly: 14628,  selfSpouse: 26122,  selfSpouse2Children: 31037 },
    { sumInsured: 750000,  ageBandId: 9,  selfOnly: 18635,  selfSpouse: 34161,  selfSpouse2Children: 39950 },
    { sumInsured: 750000,  ageBandId: 10, selfOnly: 21491,  selfSpouse: 39397,  selfSpouse2Children: 46074 },
    { sumInsured: 750000,  ageBandId: 11, selfOnly: 24858,  selfSpouse: 45569,  selfSpouse2Children: 53291 },
    { sumInsured: 1000000, ageBandId: 1,  selfOnly: 3283,   selfSpouse: 5110,   selfSpouse2Children: 7396 },
    { sumInsured: 1000000, ageBandId: 2,  selfOnly: 3579,   selfSpouse: 5576,   selfSpouse2Children: 8159 },
    { sumInsured: 1000000, ageBandId: 3,  selfOnly: 4474,   selfSpouse: 6992,   selfSpouse2Children: 9757 },
    { sumInsured: 1000000, ageBandId: 4,  selfOnly: 6532,   selfSpouse: 10762,  selfSpouse2Children: 12748 },
    { sumInsured: 1000000, ageBandId: 5,  selfOnly: 8355,   selfSpouse: 13764,  selfSpouse2Children: 16306 },
    { sumInsured: 1000000, ageBandId: 6,  selfOnly: 9854,   selfSpouse: 15326,  selfSpouse2Children: 16931 },
    { sumInsured: 1000000, ageBandId: 7,  selfOnly: 11661,  selfSpouse: 19176,  selfSpouse2Children: 25481 },
    { sumInsured: 1000000, ageBandId: 8,  selfOnly: 15941,  selfSpouse: 28442,  selfSpouse2Children: 33767 },
    { sumInsured: 1000000, ageBandId: 9,  selfOnly: 20192,  selfSpouse: 36983,  selfSpouse2Children: 43216 },
    { sumInsured: 1000000, ageBandId: 10, selfOnly: 23073,  selfSpouse: 42261,  selfSpouse2Children: 49383 },
    { sumInsured: 1000000, ageBandId: 11, selfOnly: 26688,  selfSpouse: 48882,  selfSpouse2Children: 57120 },
  ],
  11: [
    { sumInsured: 300000,  ageBandId: 12, selfOnly: 3352,   selfSpouse: 6705,   selfSpouse2Children: 10057 },
    { sumInsured: 300000,  ageBandId: 13, selfOnly: 5550,   selfSpouse: 11100,  selfSpouse2Children: 14453 },
    { sumInsured: 300000,  ageBandId: 3,  selfOnly: 6948,   selfSpouse: 13896,  selfSpouse2Children: 17248 },
    { sumInsured: 300000,  ageBandId: 4,  selfOnly: 8829,   selfSpouse: 17658,  selfSpouse2Children: 21010 },
    { sumInsured: 300000,  ageBandId: 5,  selfOnly: 9768,   selfSpouse: 19536,  selfSpouse2Children: 22888 },
    { sumInsured: 300000,  ageBandId: 6,  selfOnly: 15611,  selfSpouse: 31224,  selfSpouse2Children: 34576 },
    { sumInsured: 300000,  ageBandId: 7,  selfOnly: 21684,  selfSpouse: 43366,  selfSpouse2Children: 46719 },
    { sumInsured: 300000,  ageBandId: 8,  selfOnly: 27175,  selfSpouse: 54352,  selfSpouse2Children: 57704 },
    { sumInsured: 300000,  ageBandId: 9,  selfOnly: 31156,  selfSpouse: 62310,  selfSpouse2Children: 65663 },
    { sumInsured: 300000,  ageBandId: 10, selfOnly: 33150,  selfSpouse: 66299,  selfSpouse2Children: 69652 },
    { sumInsured: 300000,  ageBandId: 11, selfOnly: 35355,  selfSpouse: 70712,  selfSpouse2Children: 74064 },
    { sumInsured: 500000,  ageBandId: 12, selfOnly: 4633,   selfSpouse: 9265,   selfSpouse2Children: 13897 },
    { sumInsured: 500000,  ageBandId: 13, selfOnly: 6793,   selfSpouse: 13585,  selfSpouse2Children: 18218 },
    { sumInsured: 500000,  ageBandId: 3,  selfOnly: 9513,   selfSpouse: 19026,  selfSpouse2Children: 23659 },
    { sumInsured: 500000,  ageBandId: 4,  selfOnly: 12480,  selfSpouse: 24961,  selfSpouse2Children: 29593 },
    { sumInsured: 500000,  ageBandId: 5,  selfOnly: 13815,  selfSpouse: 27630,  selfSpouse2Children: 32262 },
    { sumInsured: 500000,  ageBandId: 6,  selfOnly: 21561,  selfSpouse: 43122,  selfSpouse2Children: 47755 },
    { sumInsured: 500000,  ageBandId: 7,  selfOnly: 27860,  selfSpouse: 55721,  selfSpouse2Children: 60353 },
    { sumInsured: 500000,  ageBandId: 8,  selfOnly: 34803,  selfSpouse: 69606,  selfSpouse2Children: 74237 },
    { sumInsured: 500000,  ageBandId: 9,  selfOnly: 39210,  selfSpouse: 78420,  selfSpouse2Children: 83053 },
    { sumInsured: 500000,  ageBandId: 10, selfOnly: 41615,  selfSpouse: 83230,  selfSpouse2Children: 87862 },
    { sumInsured: 500000,  ageBandId: 11, selfOnly: 44485,  selfSpouse: 88968,  selfSpouse2Children: 93601 },
    { sumInsured: 700000,  ageBandId: 12, selfOnly: 5809,   selfSpouse: 11618,  selfSpouse2Children: 17429 },
    { sumInsured: 700000,  ageBandId: 13, selfOnly: 8743,   selfSpouse: 17484,  selfSpouse2Children: 23293 },
    { sumInsured: 700000,  ageBandId: 3,  selfOnly: 12740,  selfSpouse: 25482,  selfSpouse2Children: 31291 },
    { sumInsured: 700000,  ageBandId: 4,  selfOnly: 18678,  selfSpouse: 37355,  selfSpouse2Children: 43164 },
    { sumInsured: 700000,  ageBandId: 5,  selfOnly: 20359,  selfSpouse: 40716,  selfSpouse2Children: 46526 },
    { sumInsured: 700000,  ageBandId: 6,  selfOnly: 30505,  selfSpouse: 61010,  selfSpouse2Children: 66820 },
    { sumInsured: 700000,  ageBandId: 7,  selfOnly: 39014,  selfSpouse: 78028,  selfSpouse2Children: 83838 },
    { sumInsured: 700000,  ageBandId: 8,  selfOnly: 50034,  selfSpouse: 100069, selfSpouse2Children: 105879 },
    { sumInsured: 700000,  ageBandId: 9,  selfOnly: 55892,  selfSpouse: 111784, selfSpouse2Children: 117593 },
    { sumInsured: 700000,  ageBandId: 10, selfOnly: 58569,  selfSpouse: 117140, selfSpouse2Children: 122949 },
    { sumInsured: 700000,  ageBandId: 11, selfOnly: 62948,  selfSpouse: 125897, selfSpouse2Children: 131706 },
    { sumInsured: 1000000, ageBandId: 12, selfOnly: 7148,   selfSpouse: 14297,  selfSpouse2Children: 21444 },
    { sumInsured: 1000000, ageBandId: 13, selfOnly: 10848,  selfSpouse: 21695,  selfSpouse2Children: 28844 },
    { sumInsured: 1000000, ageBandId: 3,  selfOnly: 16790,  selfSpouse: 33580,  selfSpouse2Children: 40729 },
    { sumInsured: 1000000, ageBandId: 4,  selfOnly: 24811,  selfSpouse: 49621,  selfSpouse2Children: 56770 },
    { sumInsured: 1000000, ageBandId: 5,  selfOnly: 26919,  selfSpouse: 53839,  selfSpouse2Children: 60987 },
    { sumInsured: 1000000, ageBandId: 6,  selfOnly: 38820,  selfSpouse: 77638,  selfSpouse2Children: 84787 },
    { sumInsured: 1000000, ageBandId: 7,  selfOnly: 49535,  selfSpouse: 99070,  selfSpouse2Children: 106219 },
    { sumInsured: 1000000, ageBandId: 8,  selfOnly: 61570,  selfSpouse: 123139, selfSpouse2Children: 130287 },
    { sumInsured: 1000000, ageBandId: 9,  selfOnly: 67821,  selfSpouse: 135641, selfSpouse2Children: 142789 },
    { sumInsured: 1000000, ageBandId: 10, selfOnly: 70801,  selfSpouse: 141604, selfSpouse2Children: 148751 },
    { sumInsured: 1000000, ageBandId: 11, selfOnly: 75620,  selfSpouse: 151241, selfSpouse2Children: 158389 },
  ],
  12: [
    { sumInsured: 300000,  ageBandId: 15, selfOnly: 2380,  selfSpouse: 3569,  selfSpouse2Children: 5949 },
    { sumInsured: 300000,  ageBandId: 3,  selfOnly: 3448,  selfSpouse: 5172,  selfSpouse2Children: 7552 },
    { sumInsured: 300000,  ageBandId: 16, selfOnly: 4885,  selfSpouse: 7328,  selfSpouse2Children: 9708 },
    { sumInsured: 300000,  ageBandId: 17, selfOnly: 8889,  selfSpouse: 13333, selfSpouse2Children: 15712 },
    { sumInsured: 500000,  ageBandId: 15, selfOnly: 2038,  selfSpouse: 3057,  selfSpouse2Children: 5094 },
    { sumInsured: 500000,  ageBandId: 3,  selfOnly: 2591,  selfSpouse: 3887,  selfSpouse2Children: 5925 },
    { sumInsured: 500000,  ageBandId: 16, selfOnly: 3320,  selfSpouse: 4979,  selfSpouse2Children: 7017 },
    { sumInsured: 500000,  ageBandId: 17, selfOnly: 5523,  selfSpouse: 8285,  selfSpouse2Children: 10323 },
    { sumInsured: 800000,  ageBandId: 15, selfOnly: 2207,  selfSpouse: 3311,  selfSpouse2Children: 5519 },
    { sumInsured: 800000,  ageBandId: 3,  selfOnly: 2667,  selfSpouse: 4001,  selfSpouse2Children: 6208 },
    { sumInsured: 800000,  ageBandId: 16, selfOnly: 3537,  selfSpouse: 5306,  selfSpouse2Children: 7513 },
    { sumInsured: 800000,  ageBandId: 17, selfOnly: 6699,  selfSpouse: 10049, selfSpouse2Children: 12256 },
    { sumInsured: 1000000, ageBandId: 15, selfOnly: 1885,  selfSpouse: 2827,  selfSpouse2Children: 4712 },
    { sumInsured: 1000000, ageBandId: 3,  selfOnly: 2087,  selfSpouse: 3131,  selfSpouse2Children: 5015 },
    { sumInsured: 1000000, ageBandId: 16, selfOnly: 2796,  selfSpouse: 4194,  selfSpouse2Children: 6079 },
    { sumInsured: 1000000, ageBandId: 17, selfOnly: 6211,  selfSpouse: 9316,  selfSpouse2Children: 11201 },
  ],
  38: [
    { sumInsured: 100000, selfOnly: 3484,  selfSpouse: 5923 },
    { sumInsured: 200000, selfOnly: 5575,  selfSpouse: 9481 },
    { sumInsured: 300000, selfOnly: 7902,  selfSpouse: 13432 },
    { sumInsured: 400000, selfOnly: 11612, selfSpouse: 19741 },
    { sumInsured: 500000, selfOnly: 14780, selfSpouse: 24604 },
    { sumInsured: 600000, selfOnly: 23021, selfSpouse: 37719 },
    { sumInsured: 700000, selfOnly: 32289, selfSpouse: 54343 },
  ],
  39: [
    { sumInsured: 100000, selfOnly: 2799,  selfSpouse: 4758 },
    { sumInsured: 200000, selfOnly: 4478,  selfSpouse: 7616 },
    { sumInsured: 300000, selfOnly: 6347,  selfSpouse: 10789 },
    { sumInsured: 400000, selfOnly: 9328,  selfSpouse: 15857 },
    { sumInsured: 500000, selfOnly: 11873, selfSpouse: 19764 },
    { sumInsured: 600000, selfOnly: 20097, selfSpouse: 32929 },
    { sumInsured: 700000, selfOnly: 28188, selfSpouse: 47441 },
  ],
  40: [
    { sumInsured: 100000, selfOnly: 2240,  selfSpouse: 3807 },
    { sumInsured: 200000, selfOnly: 3582,  selfSpouse: 6092 },
    { sumInsured: 300000, selfOnly: 5078,  selfSpouse: 8632 },
    { sumInsured: 400000, selfOnly: 7462,  selfSpouse: 12685 },
    { sumInsured: 500000, selfOnly: 9498,  selfSpouse: 15811 },
    { sumInsured: 600000, selfOnly: 16078, selfSpouse: 26344 },
    { sumInsured: 700000, selfOnly: 22551, selfSpouse: 37952 },
  ],
  42: [
    { sumInsured: 500000, selfOnly: 31053, selfSpouse: 41300 },
  ],
  43: [
    { sumInsured: 10000, selfOnly: 4838,  selfSpouse: 5192 },
    { sumInsured: 20000, selfOnly: 9676,  selfSpouse: 10384 },
    { sumInsured: 30000, selfOnly: 14514, selfSpouse: 15576 },
    { sumInsured: 40000, selfOnly: 23001, selfSpouse: 25010 },
  ],
  44: [
    { sumInsured: 300000,  ageBandId: 12, selfOnly: 3353,   selfSpouse: 5700,   selfSpouse2Children: 9053 },
    { sumInsured: 300000,  ageBandId: 13, selfOnly: 5550,   selfSpouse: 9435,   selfSpouse2Children: 12788 },
    { sumInsured: 300000,  ageBandId: 3,  selfOnly: 6948,   selfSpouse: 11812,  selfSpouse2Children: 15165 },
    { sumInsured: 300000,  ageBandId: 4,  selfOnly: 14357,  selfSpouse: 24408,  selfSpouse2Children: 27761 },
    { sumInsured: 300000,  ageBandId: 5,  selfOnly: 17379,  selfSpouse: 29545,  selfSpouse2Children: 32898 },
    { sumInsured: 300000,  ageBandId: 6,  selfOnly: 27777,  selfSpouse: 47221,  selfSpouse2Children: 50574 },
    { sumInsured: 300000,  ageBandId: 7,  selfOnly: 39409,  selfSpouse: 66995,  selfSpouse2Children: 70348 },
    { sumInsured: 300000,  ageBandId: 8,  selfOnly: 49392,  selfSpouse: 83966,  selfSpouse2Children: 87319 },
    { sumInsured: 300000,  ageBandId: 9,  selfOnly: 56624,  selfSpouse: 96260,  selfSpouse2Children: 99613 },
    { sumInsured: 300000,  ageBandId: 10, selfOnly: 60250,  selfSpouse: 102424, selfSpouse2Children: 105777 },
    { sumInsured: 300000,  ageBandId: 11, selfOnly: 64257,  selfSpouse: 109237, selfSpouse2Children: 112590 },
    { sumInsured: 500000,  ageBandId: 12, selfOnly: 4632,   selfSpouse: 7874,   selfSpouse2Children: 12506 },
    { sumInsured: 500000,  ageBandId: 13, selfOnly: 6793,   selfSpouse: 11548,  selfSpouse2Children: 16180 },
    { sumInsured: 500000,  ageBandId: 3,  selfOnly: 9513,   selfSpouse: 16172,  selfSpouse2Children: 20804 },
    { sumInsured: 500000,  ageBandId: 4,  selfOnly: 20295,  selfSpouse: 34501,  selfSpouse2Children: 39133 },
    { sumInsured: 500000,  ageBandId: 5,  selfOnly: 24580,  selfSpouse: 41786,  selfSpouse2Children: 46418 },
    { sumInsured: 500000,  ageBandId: 6,  selfOnly: 38362,  selfSpouse: 65215,  selfSpouse2Children: 69847 },
    { sumInsured: 500000,  ageBandId: 7,  selfOnly: 50635,  selfSpouse: 86080,  selfSpouse2Children: 90712 },
    { sumInsured: 500000,  ageBandId: 8,  selfOnly: 63254,  selfSpouse: 107532, selfSpouse2Children: 112164 },
    { sumInsured: 500000,  ageBandId: 9,  selfOnly: 71264,  selfSpouse: 121148, selfSpouse2Children: 125780 },
    { sumInsured: 500000,  ageBandId: 10, selfOnly: 75635,  selfSpouse: 128579, selfSpouse2Children: 133211 },
    { sumInsured: 500000,  ageBandId: 11, selfOnly: 80849,  selfSpouse: 137443, selfSpouse2Children: 142075 },
    { sumInsured: 700000,  ageBandId: 12, selfOnly: 5809,   selfSpouse: 9875,   selfSpouse2Children: 15684 },
    { sumInsured: 700000,  ageBandId: 13, selfOnly: 8742,   selfSpouse: 14861,  selfSpouse2Children: 20670 },
    { sumInsured: 700000,  ageBandId: 3,  selfOnly: 12741,  selfSpouse: 21660,  selfSpouse2Children: 27469 },
    { sumInsured: 700000,  ageBandId: 4,  selfOnly: 30374,  selfSpouse: 51635,  selfSpouse2Children: 57444 },
    { sumInsured: 700000,  ageBandId: 5,  selfOnly: 36221,  selfSpouse: 61576,  selfSpouse2Children: 67385 },
    { sumInsured: 700000,  ageBandId: 6,  selfOnly: 54275,  selfSpouse: 92268,  selfSpouse2Children: 98077 },
    { sumInsured: 700000,  ageBandId: 7,  selfOnly: 70907,  selfSpouse: 120543, selfSpouse2Children: 126352 },
    { sumInsured: 700000,  ageBandId: 8,  selfOnly: 90938,  selfSpouse: 154594, selfSpouse2Children: 160403 },
    { sumInsured: 700000,  ageBandId: 9,  selfOnly: 101583, selfSpouse: 172691, selfSpouse2Children: 178500 },
    { sumInsured: 700000,  ageBandId: 10, selfOnly: 106450, selfSpouse: 180965, selfSpouse2Children: 186774 },
    { sumInsured: 700000,  ageBandId: 11, selfOnly: 114407, selfSpouse: 194492, selfSpouse2Children: 200301 },
    { sumInsured: 1000000, ageBandId: 12, selfOnly: 7148,   selfSpouse: 12152,  selfSpouse2Children: 19300 },
    { sumInsured: 1000000, ageBandId: 13, selfOnly: 10848,  selfSpouse: 18442,  selfSpouse2Children: 25590 },
    { sumInsured: 1000000, ageBandId: 3,  selfOnly: 16790,  selfSpouse: 28543,  selfSpouse2Children: 35691 },
    { sumInsured: 1000000, ageBandId: 4,  selfOnly: 40347,  selfSpouse: 68590,  selfSpouse2Children: 75738 },
    { sumInsured: 1000000, ageBandId: 5,  selfOnly: 47895,  selfSpouse: 81421,  selfSpouse2Children: 88569 },
    { sumInsured: 1000000, ageBandId: 6,  selfOnly: 69068,  selfSpouse: 117415, selfSpouse2Children: 124563 },
    { sumInsured: 1000000, ageBandId: 7,  selfOnly: 88134,  selfSpouse: 149827, selfSpouse2Children: 156975 },
    { sumInsured: 1000000, ageBandId: 8,  selfOnly: 111903, selfSpouse: 190234, selfSpouse2Children: 197382 },
    { sumInsured: 1000000, ageBandId: 9,  selfOnly: 123264, selfSpouse: 209548, selfSpouse2Children: 216696 },
    { sumInsured: 1000000, ageBandId: 10, selfOnly: 128682, selfSpouse: 218759, selfSpouse2Children: 225907 },
    { sumInsured: 1000000, ageBandId: 11, selfOnly: 137438, selfSpouse: 233645, selfSpouse2Children: 240793 },
  ],
  45: [
    { sumInsured: 300000,  ageBandId: 15, selfOnly: 5373,  selfSpouse: 8060,  selfSpouse2Children: 10746 },
    { sumInsured: 300000,  ageBandId: 3,  selfOnly: 5910,  selfSpouse: 8866,  selfSpouse2Children: 11821 },
    { sumInsured: 300000,  ageBandId: 16, selfOnly: 6501,  selfSpouse: 9752,  selfSpouse2Children: 13003 },
    { sumInsured: 300000,  ageBandId: 17, selfOnly: 7152,  selfSpouse: 10727, selfSpouse2Children: 14303 },
    { sumInsured: 500000,  ageBandId: 15, selfOnly: 6448,  selfSpouse: 9672,  selfSpouse2Children: 12896 },
    { sumInsured: 500000,  ageBandId: 3,  selfOnly: 7093,  selfSpouse: 10639, selfSpouse2Children: 14185 },
    { sumInsured: 500000,  ageBandId: 16, selfOnly: 7802,  selfSpouse: 11703, selfSpouse2Children: 15604 },
    { sumInsured: 500000,  ageBandId: 17, selfOnly: 8582,  selfSpouse: 12873, selfSpouse2Children: 17164 },
    { sumInsured: 800000,  ageBandId: 15, selfOnly: 7737,  selfSpouse: 11606, selfSpouse2Children: 15475 },
    { sumInsured: 800000,  ageBandId: 3,  selfOnly: 8511,  selfSpouse: 12767, selfSpouse2Children: 17022 },
    { sumInsured: 800000,  ageBandId: 16, selfOnly: 9362,  selfSpouse: 14043, selfSpouse2Children: 18724 },
    { sumInsured: 800000,  ageBandId: 17, selfOnly: 10298, selfSpouse: 15448, selfSpouse2Children: 20597 },
    { sumInsured: 1000000, ageBandId: 15, selfOnly: 9285,  selfSpouse: 13927, selfSpouse2Children: 18570 },
    { sumInsured: 1000000, ageBandId: 3,  selfOnly: 10213, selfSpouse: 15320, selfSpouse2Children: 20426 },
    { sumInsured: 1000000, ageBandId: 16, selfOnly: 11235, selfSpouse: 16852, selfSpouse2Children: 22469 },
    { sumInsured: 1000000, ageBandId: 17, selfOnly: 12358, selfSpouse: 18537, selfSpouse2Children: 24716 },
  ],
  46: [
    { sumInsured: 100000, selfOnly: 2000, selfSpouse: 2500 },
    { sumInsured: 500000, selfOnly: 5000, selfSpouse: 5500 },
  ],
  47: [
    { sumInsured: 100, selfOnly: 1, selfSpouse: 2 },
  ],
  48: [
    { sumInsured: 500000,  selfOnly: 4250,  selfSpouse: 6800  },
    { sumInsured: 1000000, selfOnly: 7500,  selfSpouse: 12000 },
    { sumInsured: 1500000, selfOnly: 10800, selfSpouse: 17300 },
    { sumInsured: 2000000, selfOnly: 14200, selfSpouse: 22700 },
  ],
}

// Rich brochure content keyed by productId — shown in "View Details" modal.
export const PRODUCT_DETAILS = {
  3: {
    tagline: 'Extra Coverage When Your Base Policy Runs Out',
    eligibilityCriteria: 'Available to individuals aged 18–65 years who hold an existing base health insurance policy or corporate group cover. Dependent children can be added between 91 days and 25 years.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months. Specific illnesses such as cataract and hernia covered after 12 months.',
    copayment: 'No mandatory copayment for members below 60 years. 10% copay applies for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this Super Top Up policy.',
    description: 'Go Digit\'s Super Top Up Policy kicks in once you\'ve exhausted your base health plan, giving you ₹1L–₹10L of additional hospitalisation coverage. It\'s the most cost-effective way to achieve high total cover — perfect as a top-up over any existing corporate or individual health plan.',
    target: ['Employees with corporate health insurance', 'Individuals with an existing base health plan', 'Families wanting ₹10L+ total coverage affordably'],
    benefits: [
      'Activates after deductible/base plan exhaustion',
      'In-patient hospitalisation fully covered',
      'Pre-hospitalisation (30 days) & post-hospitalisation (60 days)',
      'Day care procedures — 540+ treatments listed',
      'Ambulance charges covered',
      'Covers self and spouse',
    ],
    covered: ['In-patient hospitalisation (above threshold)', 'Surgical & procedure charges', 'ICU and critical care charges', 'Pre-hospitalisation (30 days)', 'Post-hospitalisation (60 days)', 'Day care treatments', 'Ambulance expenses'],
    notCovered: ['Expenses below deductible/threshold', 'Pre-existing diseases (first 2 years)', 'Cosmetic & plastic surgery', 'OPD consultations', 'Dental (unless accidental)', 'Self-inflicted injuries'],
    highlights: [
      { label: 'Sum Insured', value: '₹1L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹2,430/yr', icon: '💰' },
      { label: 'Coverage', value: 'Self + Spouse', icon: '👥' },
      { label: 'Insurer', value: 'Go Digit', icon: '🏢' },
    ],
  },
  7: {
    tagline: 'Everyday Healthcare Costs — Finally Covered',
    eligibilityCriteria: 'Open to individuals and family members aged 91 days to 65 years. Can be purchased as a standalone OPD cover or alongside a base hospitalisation policy.',
    waitingPeriods: '30-day initial waiting period for all OPD claims. Dental and vision OPD sub-limits apply after a 90-day waiting period.',
    copayment: 'No copayment applicable — the full OPD limit is reimbursed as per policy sub-limits.',
    maternityBenefits: 'Maternity-related consultations are not covered under this OPD policy.',
    description: 'Go Digit\'s Out-Patient Care Insurance Policy covers the day-to-day medical expenses that standard hospitalisation policies ignore: doctor visits, diagnostics, pharmacy bills, and preventive check-ups. The perfect add-on for anyone whose base plan leaves OPD uncovered.',
    target: ['Salaried professionals with hospitalisation-only cover', 'Families with frequent doctor visits', 'Anyone wanting to cover routine medical spending'],
    benefits: [
      'Doctor consultation fees (GP & specialist)',
      'Diagnostic tests and lab investigations',
      'Prescribed medicines and pharmacy',
      'Preventive annual health check-ups',
      'Physiotherapy sessions',
      'Vision and dental OPD (limited)',
    ],
    covered: ['GP and specialist consultations', 'Laboratory & diagnostic tests', 'Prescribed medicines', 'Physiotherapy sessions', 'Preventive health check-ups', 'Minor outpatient procedures'],
    notCovered: ['In-patient hospitalisation', 'Cosmetic procedures', 'Pre-existing OPD claims (1st year)', 'Vitamins/supplements unless prescribed', 'Experimental treatments'],
    highlights: [
      { label: 'OPD Limit', value: '₹15K – ₹20K', icon: '💊' },
      { label: 'Premium From', value: '₹10,385/yr', icon: '💰' },
      { label: 'Coverage', value: 'Self / Couple', icon: '👥' },
      { label: 'Insurer', value: 'Go Digit', icon: '🏢' },
    ],
  },
  8: {
    tagline: 'Your EMIs Stay Covered Even When You Can\'t Work',
    eligibilityCriteria: 'Available to salaried and self-employed individuals aged 21–60 years with an active loan or EMI obligation.',
    waitingPeriods: 'No waiting period for accidental hospitalisation or disability claims. A 90-day waiting period applies for illness-related claims where covered.',
    copayment: 'No copayment applicable on approved claims.',
    maternityBenefits: 'Not applicable — this is an income/EMI protection policy, not a health policy.',
    description: 'Go Digit\'s Payment Protection Policy ensures your financial obligations are protected in the event of accidental hospitalisation or disability. It pays out a benefit to cover your loan EMIs or daily expenses while you recover — giving you peace of mind during tough times.',
    target: ['Loan and EMI payers', 'Self-employed professionals', 'Anyone with outstanding financial liabilities'],
    benefits: [
      'Lump-sum or daily cash benefit on hospitalisation',
      'Covers EMI obligations during claim period',
      'Accidental total and partial disablement cover',
      'No pre-medical check-up required at entry',
      'Quick and simple claims process',
      'Worldwide accidental coverage',
    ],
    covered: ['Accidental hospitalisation benefit', 'Temporary total disablement', 'Accidental partial disablement', 'Loan/EMI obligations during recovery'],
    notCovered: ['Illness-related disability (non-accidental)', 'Pre-existing conditions', 'Self-inflicted injuries', 'War or nuclear events', 'Loan amounts beyond policy limit'],
    highlights: [
      { label: 'Cover', value: '₹50K – ₹1L', icon: '🛡️' },
      { label: 'Premium From', value: '₹998/yr', icon: '💰' },
      { label: 'Coverage', value: 'Self Only', icon: '👤' },
      { label: 'Insurer', value: 'Go Digit', icon: '🏢' },
    ],
  },
  9: {
    tagline: 'Comprehensive Group Health for BPP Employees',
    eligibilityCriteria: 'Available to BPP employees aged 18–65 years and their dependents (spouse and up to 2 children). New joiners are covered from date of enrolment.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 12 months under group continuity. Specific illnesses covered after 90 days.',
    copayment: 'No copayment for members below 60 years. 10% copay applies for dependents aged 60 years and above.',
    maternityBenefits: 'Available as an optional rider — normal delivery covered up to ₹25,000 and caesarean up to ₹35,000, after a 9-month waiting period.',
    description: 'MAGMA\'s Group Health Insurance for BPP provides full hospitalisation coverage for employees and their families. With 11 age bands ensuring fair premiums and sum insured from ₹3L to ₹10L, it is the preferred choice for BPP workforce health protection.',
    target: ['BPP employees and their families', 'HR teams enrolling group cover', 'Employees aged 18 – 65 across all age groups'],
    benefits: [
      'In-patient hospitalisation fully covered',
      'Day care procedures (540+ listed)',
      'Pre-hospitalisation (30 days) & post (60 days)',
      'Maternity benefit available as optional rider',
      'Newborn cover from day one',
      'Cashless access at 5,000+ network hospitals',
      'AYUSH treatments covered',
    ],
    covered: ['All hospitalisation expenses', 'ICU and critical care', 'Surgeon & anaesthetist fees', 'Blood, oxygen & operation theatre', 'Room rent (single private AC room)', 'Organ donor expenses', 'AYUSH treatments'],
    notCovered: ['Pre-existing diseases (1st year)', 'Cosmetic & plastic surgery', 'Dental unless accidental', 'Self-inflicted injuries', 'Infertility treatment', 'Experimental therapies'],
    highlights: [
      { label: 'Sum Insured', value: '₹3L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹8,459/yr', icon: '💰' },
      { label: 'Age Bands', value: '11 bands', icon: '📊' },
      { label: 'Insurer', value: 'MAGMA', icon: '🏢' },
    ],
  },
  10: {
    tagline: 'Amplify Your BPP Coverage with a Cost-Effective Top-Up',
    eligibilityCriteria: 'Available to BPP employees aged 18–65 years with an existing base health policy. Spouse and up to 2 children can be covered.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this top-up policy.',
    description: 'MAGMA\'s Standalone Super Top Up for BPP employees extends your protection beyond the base policy limit. With 11 age bands and sum insured options from ₹3L to ₹10L, it fills the coverage gap at a significantly lower premium than upgrading your base plan.',
    target: ['BPP employees with an existing base health cover', 'Employees aged 30+ seeking higher sum insured', 'Families wanting ₹13L+ combined protection'],
    benefits: [
      'Activates when base plan is exhausted',
      'Wide sum insured options: ₹3L – ₹10L',
      'Covers employee, spouse and two children',
      'In-patient and day care treatments covered',
      'Pre (30 days) & post-hospitalisation (60 days)',
      'Age-appropriate premium for all bands',
    ],
    covered: ['Hospitalisation above threshold', 'Day care procedures', 'Pre-hospitalisation (30 days)', 'Post-hospitalisation (60 days)', 'Surgical expenses', 'ICU charges'],
    notCovered: ['Expenses within deductible', 'OPD consultations', 'Pre-existing diseases (1st year)', 'Cosmetic surgery', 'Dental unless accident'],
    highlights: [
      { label: 'Sum Insured', value: '₹3L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹2,538/yr', icon: '💰' },
      { label: 'Age Bands', value: '11 bands', icon: '📊' },
      { label: 'Insurer', value: 'MAGMA', icon: '🏢' },
    ],
  },
  11: {
    tagline: 'Oriental Insurance — Trusted Group Health for BPP',
    eligibilityCriteria: 'Available to BPP employee groups of 7 or more members, aged 18–65 years, along with spouse and dependent children.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 12 months under group continuity.',
    copayment: 'No copayment for members below 60 years. 10% copay applies for dependents aged 60 and above.',
    maternityBenefits: 'Available as an optional rider — covers normal and caesarean delivery up to ₹30,000 after a 9-month waiting period.',
    description: 'Oriental Insurance Company\'s Group Health Policy for BPP employees offers comprehensive in-patient coverage backed by one of India\'s oldest public sector insurers. Age-banded pricing with sum insured from ₹3L to ₹10L ensures affordable protection for all age groups.',
    target: ['BPP employees and family members', 'Groups of 7+ members seeking corporate cover', 'Employees aged 18 – 65'],
    benefits: [
      'Comprehensive in-patient hospitalisation',
      'Cashless access at 3,000+ Oriental network hospitals',
      'All day care treatments covered',
      'Pre (30 days) & post (60 days) hospitalisation',
      'Ambulance charges covered',
      'AYUSH treatments included',
      'Optional maternity rider available',
    ],
    covered: ['All hospitalisation expenses', 'ICU and critical care', 'Room rent (as per limits)', 'Surgical and procedure charges', 'Day care treatments (listed)', 'Pre & post-hospitalisation'],
    notCovered: ['Pre-existing diseases (1st year)', 'Cosmetic & plastic surgery', 'Dental unless accidental', 'Spectacles and contact lenses', 'Vaccination and immunisation', 'Self-inflicted injury'],
    highlights: [
      { label: 'Sum Insured', value: '₹3L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹3,352/yr', icon: '💰' },
      { label: 'Age Bands', value: '11 bands', icon: '📊' },
      { label: 'Insurer', value: 'Oriental', icon: '🏢' },
    ],
  },
  12: {
    tagline: 'Top Up Your Oriental BPP Cover — Smarter, Cheaper',
    eligibilityCriteria: 'Available to BPP employees aged 18–65 years with existing Oriental base cover. Spouse and up to 2 children can be included.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this super top-up policy.',
    description: 'Oriental Insurance\'s Super Top Up for BPP gives you extended hospitalisation coverage once your base plan limit is reached. With 4 age bands and sum insured from ₹3L to ₹10L, it\'s a smart, affordable way to achieve higher combined protection.',
    target: ['BPP employees with existing Oriental base cover', 'Employees seeking higher total coverage', 'Families wanting ₹13L+ combined sum insured'],
    benefits: [
      'Super top-up activates post base plan exhaustion',
      '4 age-band premium structure for fairness',
      'Sum insured: ₹3L, ₹5L, ₹8L and ₹10L options',
      'Covers employee, spouse and two children',
      'All hospitalisation & day care covered',
      'Annual renewal with continuity benefits',
    ],
    covered: ['Hospitalisation above threshold', 'Surgical expenses', 'ICU charges', 'Day care treatments', 'Pre (30 days) & post (60 days) hospitalisation'],
    notCovered: ['Expenses within deductible', 'OPD consultations', 'Pre-existing diseases (1st year)', 'Cosmetic procedures', 'Dental unless accidental'],
    highlights: [
      { label: 'Sum Insured', value: '₹3L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹1,885/yr', icon: '💰' },
      { label: 'Age Bands', value: '4 bands', icon: '📊' },
      { label: 'Insurer', value: 'Oriental', icon: '🏢' },
    ],
  },
  38: {
    tagline: 'SBI Super Top Up — Enhanced Cover from ₹3L Threshold',
    eligibilityCriteria: 'Available to policyholders aged 18–65 years holding an existing base health policy with a ₹3L sum insured.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this Super Top Up policy.',
    description: 'SBI General\'s Super Top Up Policy (₹3L threshold) covers all hospitalisation expenses beyond your ₹3L base plan. The most accessible entry point into SBI\'s Super Top Up range — ideal for those with a ₹3L group or individual base cover.',
    target: ['Policyholders with ₹3L base health cover', 'Individuals wanting to extend to ₹10L total', 'Budget-conscious families seeking high cover'],
    benefits: [
      'Covers hospitalisation expenses above ₹3L deductible',
      'Sum insured options: ₹1L – ₹7L additional',
      'Self and spouse coverage',
      'All standard hospitalisation expenses',
      'Day care procedures covered',
      'Pre (60 days) & post (90 days) hospitalisation',
      'SBI\'s wide cashless hospital network',
    ],
    covered: ['Hospitalisation beyond ₹3L threshold', 'ICU and surgical charges', 'Day care procedures', 'Pre-hospitalisation (60 days)', 'Post-hospitalisation (90 days)', 'Ambulance charges'],
    notCovered: ['Expenses within ₹3L deductible', 'OPD consultations', 'Pre-existing diseases (2 years)', 'Cosmetic surgery', 'Dental unless accident', 'Self-inflicted injuries'],
    highlights: [
      { label: 'Threshold', value: '₹3 Lakh', icon: '🎯' },
      { label: 'Add-on Cover', value: '₹1L – ₹7L', icon: '🛡️' },
      { label: 'Premium From', value: '₹3,484/yr', icon: '💰' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
  39: {
    tagline: 'SBI Super Top Up — Seamless Extension from ₹4L Base',
    eligibilityCriteria: 'Available to policyholders aged 18–65 years holding an existing base health policy with a ₹4L sum insured.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this Super Top Up policy.',
    description: 'SBI General\'s Super Top Up with ₹4L threshold perfectly complements a ₹4L base policy. Once your base plan is exhausted, this policy takes over — covering hospitalisation up to ₹11L total at a fraction of the cost of a standalone high-SI plan.',
    target: ['Policyholders with ₹4L base health cover', 'Those wanting up to ₹11L total protection', 'Families needing affordable high-value cover'],
    benefits: [
      'Activates post ₹4L base plan exhaustion',
      'Sum insured options: ₹1L – ₹7L additional',
      'Self and spouse coverage',
      'Comprehensive hospitalisation coverage',
      'Day care procedures included',
      'SBI cashless network access',
    ],
    covered: ['Hospitalisation beyond ₹4L threshold', 'ICU and surgical charges', 'Day care procedures', 'Pre-hospitalisation (60 days)', 'Post-hospitalisation (90 days)', 'Ambulance charges'],
    notCovered: ['Expenses within ₹4L deductible', 'OPD consultations', 'Pre-existing diseases (2 years)', 'Cosmetic surgery', 'Dental unless accident'],
    highlights: [
      { label: 'Threshold', value: '₹4 Lakh', icon: '🎯' },
      { label: 'Add-on Cover', value: '₹1L – ₹7L', icon: '🛡️' },
      { label: 'Premium From', value: '₹2,799/yr', icon: '💰' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
  40: {
    tagline: 'SBI Super Top Up — Maximum Value from ₹5L Base Plan',
    eligibilityCriteria: 'Available to policyholders aged 18–65 years holding an existing base health policy with a ₹5L sum insured.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this Super Top Up policy.',
    description: 'SBI General\'s Super Top Up with ₹5L threshold is the most cost-effective option in the range for those with a ₹5L base policy. Achieve total health coverage up to ₹12L while paying only a minimal additional premium.',
    target: ['Policyholders with ₹5L base health cover', 'Cost-conscious buyers seeking high total SI', 'Families wanting ₹12L total coverage cheaply'],
    benefits: [
      'Activates after ₹5L base plan is exhausted',
      'Sum insured options: ₹1L – ₹7L additional',
      'Self and spouse coverage',
      'All hospitalisation expenses covered',
      'Day care procedures included',
      'No room rent sub-limit',
    ],
    covered: ['Hospitalisation beyond ₹5L threshold', 'ICU and surgical charges', 'Day care procedures', 'Pre-hospitalisation (60 days)', 'Post-hospitalisation (90 days)', 'Ambulance charges'],
    notCovered: ['Expenses within ₹5L deductible', 'OPD consultations', 'Pre-existing diseases (2 years)', 'Cosmetic surgery', 'Dental unless accident'],
    highlights: [
      { label: 'Threshold', value: '₹5 Lakh', icon: '🎯' },
      { label: 'Add-on Cover', value: '₹1L – ₹7L', icon: '🛡️' },
      { label: 'Premium From', value: '₹2,240/yr', icon: '💰' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
  42: {
    tagline: 'SBI Base Policy — A Trusted Foundation for Your Health',
    eligibilityCriteria: 'Available to individuals and family members aged 18–65 years. Dependent children can be covered from 91 days to 25 years. Lifetime renewability guaranteed.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months. Specific illnesses such as cataract, hernia and joint replacement covered after 12 months.',
    copayment: 'No copayment for members below 60 years. 10% copay applies for members aged 60 years and above.',
    maternityBenefits: 'Not covered as standard — can be added as an optional rider covering normal and caesarean delivery after a 9-month waiting period.',
    description: 'SBI General\'s Base Health Policy offers solid ₹5 lakh hospitalisation coverage backed by one of India\'s largest public sector banks. With access to 6,000+ cashless hospitals, an annual health check-up benefit, and no-claim bonus, it\'s the right foundation to build your health cover on.',
    target: ['Individuals and families aged 18 – 65', 'First-time health insurance buyers', 'Those wanting PSU-backed insurance reliability'],
    benefits: [
      '₹5 lakh sum insured',
      'Cashless access at 6,000+ SBI network hospitals',
      'Annual health check-up included',
      'No-claim bonus: 25% per year, up to 50%',
      'Day care procedures covered',
      'Domiciliary hospitalisation covered',
      'AYUSH treatments included',
    ],
    covered: ['In-patient hospitalisation', 'Day care procedures (listed)', 'Pre-hospitalisation (60 days)', 'Post-hospitalisation (90 days)', 'Ambulance charges', 'Domiciliary hospitalisation', 'AYUSH treatment'],
    notCovered: ['Pre-existing diseases (2 years)', 'Cosmetic surgery', 'Dental unless accidental', 'Maternity (unless added as rider)', 'Obesity treatment', 'Self-inflicted injuries'],
    highlights: [
      { label: 'Sum Insured', value: '₹5 Lakh', icon: '🛡️' },
      { label: 'Premium From', value: '₹31,053/yr', icon: '💰' },
      { label: 'Coverage', value: 'Self / Couple', icon: '👥' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
  43: {
    tagline: 'SBI OPD 2025-26 — Your Everyday Health Bills Covered',
    eligibilityCriteria: 'Available to individuals and family members aged 91 days to 65 years, either standalone or alongside a hospitalisation policy.',
    waitingPeriods: '30-day initial waiting period applies to all OPD claims.',
    copayment: 'No copayment applicable — OPD expenses are reimbursed as per policy sub-limits.',
    maternityBenefits: 'Maternity-related consultations are not covered under this OPD policy.',
    description: 'SBI General\'s OPD Policy for 2025-26 covers the routine medical expenses that standard hospitalisation plans miss — consultations, diagnostics, pharmacy, and preventive health checks. A must-have complement to any hospitalisation-only policy.',
    target: ['Working professionals with frequent OPD needs', 'Families with children requiring routine check-ups', 'Anyone with a hospitalisation plan lacking OPD cover'],
    benefits: [
      'Doctor consultation reimbursement (GP & specialist)',
      'Diagnostic tests and lab investigations',
      'Prescribed medicines and pharmacy',
      'Annual preventive health check-up',
      'Physiotherapy sessions covered',
      'Vision and dental OPD (limited)',
    ],
    covered: ['GP and specialist consultations', 'Lab tests and diagnostics', 'Prescribed medicines', 'Physiotherapy', 'Annual health check-ups', 'Minor OPD procedures'],
    notCovered: ['In-patient hospitalisation expenses', 'Cosmetic procedures', 'Pre-existing OPD claims (1st year)', 'Vitamins/supplements unless prescribed', 'Experimental treatments'],
    highlights: [
      { label: 'OPD Limit', value: '₹10K – ₹40K', icon: '💊' },
      { label: 'Premium From', value: '₹4,838/yr', icon: '💰' },
      { label: 'Coverage', value: 'Self / Couple', icon: '👥' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
  44: {
    tagline: 'SBI Group Health for BPP — 2026-27 Policy Year',
    eligibilityCriteria: 'Available to BPP employees aged 18–65 years enrolling for the 2026-27 policy year, along with spouse and up to 2 children.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 12 months under group continuity.',
    copayment: 'No copayment for members below 60 years. 10% copay applies for dependents aged 60 and above.',
    maternityBenefits: 'Available as an optional add-on — covers normal and caesarean delivery up to ₹30,000 after a 9-month waiting period.',
    description: 'SBI General\'s Group Health Insurance for BPP employees for the 2026-27 policy year. Comprehensive in-patient coverage with 11 age bands, sum insured from ₹3L to ₹10L, and cashless access across SBI\'s extensive 6,000+ hospital network.',
    target: ['BPP employees enrolling for 2026-27', 'Employee families — spouse and up to 2 children', 'New joiners requiring immediate health coverage'],
    benefits: [
      'Comprehensive in-patient hospitalisation',
      '11 age bands for fair premium pricing',
      'Cashless at 6,000+ SBI network hospitals',
      'Day care procedures (540+ listed)',
      'Pre (60 days) & post (90 days) hospitalisation',
      'Maternity benefit as optional add-on',
      'Newborn cover from day one',
      'AYUSH treatments included',
    ],
    covered: ['All in-patient hospitalisation', 'Day care procedures', 'ICU and surgical charges', 'Pre-hospitalisation (60 days)', 'Post-hospitalisation (90 days)', 'Ambulance charges', 'Room rent (single private AC room)', 'Organ donor expenses'],
    notCovered: ['Pre-existing diseases (1st year)', 'Cosmetic surgery', 'Dental unless accidental', 'Self-inflicted injuries', 'Infertility treatment', 'Experimental therapies', 'Spectacles and contact lenses'],
    highlights: [
      { label: 'Sum Insured', value: '₹3L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹3,353/yr', icon: '💰' },
      { label: 'Age Bands', value: '11 bands', icon: '📊' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
  48: {
    tagline: 'Smart Top-Up — 15% Bundle Savings with SBI Base Policy',
    eligibilityCriteria: 'Available to existing SBI Base Policy (KMD-042) holders aged 18–65 years. Spouse and up to 2 children can be included.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this top-up policy.',
    description: 'SBI Arogya Plus is a dedicated Top Up Health Plan engineered to pair with the SBI Base Policy (KMD-042). Once your base plan limit is exhausted, it kicks in seamlessly — adding ₹5L to ₹20L of hospitalisation coverage at a fraction of the standalone cost. Campaigns that include both this plan and the SBI Base Policy automatically unlock a 15% bundle discount on the top-up premium.',
    target: [
      'SBI Base Policy holders wanting higher total coverage',
      'Members seeking ₹10L – ₹25L combined hospitalisation cover',
      'Families wanting maximum protection at minimal extra cost',
      'First-time top-up buyers who already hold an SBI base plan',
    ],
    benefits: [
      'Activates only after SBI Base Policy (KMD-042) is exhausted',
      '15% bundle discount when paired with SBI Base Policy in campaign',
      'Sum insured options: ₹5L, ₹10L, ₹15L and ₹20L',
      'Covers self, spouse, and up to 2 children',
      'In-patient and day care hospitalisation covered',
      'Pre-hospitalisation (60 days) & post-hospitalisation (90 days)',
      'Cashless access at 6,000+ SBI network hospitals',
      'Annual renewal with continuity benefit bonus',
    ],
    covered: [
      'Hospitalisation beyond SBI Base Policy limit',
      'ICU and critical care charges',
      'Surgical and procedure expenses',
      'Day care treatments (540+ listed)',
      'Pre-hospitalisation (60 days)',
      'Post-hospitalisation (90 days)',
      'Ambulance charges',
    ],
    notCovered: [
      'Expenses below the base policy deductible',
      'OPD consultations',
      'Pre-existing diseases (first year)',
      'Cosmetic or plastic surgery',
      'Dental treatment (unless accidental)',
      'Self-inflicted injuries or war events',
    ],
    highlights: [
      { label: 'Sum Insured',    value: '₹5L – ₹20L', icon: '🛡️' },
      { label: 'Premium From',   value: '₹4,250/yr',   icon: '💰' },
      { label: 'Bundle Discount',value: '15% off',      icon: '🏷️' },
      { label: 'Pairs With',     value: 'KMD-042',      icon: '🔗' },
    ],
  },
  45: {
    tagline: 'SBI Super Top Up BPP 2026-27 — Go Beyond Your Base Cover',
    eligibilityCriteria: 'Available to BPP employees aged 18–65 years with the 2026-27 base group cover. Spouse and up to 2 children can be included.',
    waitingPeriods: 'Initial waiting period of 30 days (waived for accidents). Pre-existing diseases covered after 24 months.',
    copayment: 'No copayment for members below 60 years. 10% copay for members aged 60 years and above.',
    maternityBenefits: 'Maternity expenses are not covered under this super top-up policy.',
    description: 'SBI General\'s Super Top Up for BPP employees in 2026-27 extends your group health coverage beyond the base plan limit. With 4 age bands and sum insured from ₹3L to ₹10L, it\'s designed to give BPP employees meaningful higher protection at an affordable additional premium.',
    target: ['BPP employees with the 2026-27 base group cover', 'Employees wanting total coverage of ₹13L+', 'Families seeking higher combined protection'],
    benefits: [
      'Top-up coverage activates post base plan exhaustion',
      '4 age-band premium structure',
      'Sum insured: ₹3L, ₹5L, ₹8L and ₹10L options',
      'Covers employee, spouse and two children',
      'All hospitalisation and day care covered',
      'Annual renewal with continuity bonus',
    ],
    covered: ['Hospitalisation above base threshold', 'Surgical and ICU expenses', 'Day care procedures', 'Pre-hospitalisation (60 days)', 'Post-hospitalisation (90 days)', 'Ambulance charges'],
    notCovered: ['Expenses within deductible', 'OPD consultations', 'Pre-existing diseases (1st year)', 'Cosmetic procedures', 'Dental unless accidental'],
    highlights: [
      { label: 'Sum Insured', value: '₹3L – ₹10L', icon: '🛡️' },
      { label: 'Premium From', value: '₹5,373/yr', icon: '💰' },
      { label: 'Age Bands', value: '4 bands', icon: '📊' },
      { label: 'Insurer', value: 'SBI General', icon: '🏢' },
    ],
  },
}
